# Generated by Django 5.1.5 on 2025-02-05 01:35

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=project.models.image_directory_path),
        ),
    ]
